site_name: bayes_traj Documentation
site_url: https://github.com/acil-bwh/bayes_traj
theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
nav:
  - Home: index.md
  - Formulation: formulation.md
  - Inference: inference.md
  - Tutorial: bayes_traj_tutorial.md  
plugins:
  - search
  - git-revision-date
  - bibtex:
      bib_file: "references.bib"      			
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
